---
title: "Teaching"

---
## Teaching 

I teach the full range of MPA core course work, but primarily teach courses in Local Government Management, Public Budgeting, and Data Analysis. I focus on teaching concepts, their practical application, and the development of actionable skills. As a neurodivergent individual (i.e., ADHD), I understand the importance of inclusiveness and diversity in my courses. I use a two prong approach: inclusion by design (i.e., exploration of course content, text, and subtext promoting diverse opinions), and inclusion through process (i.e., using classroom management techniques to create an inclusive learning environment). I love teaching the current and next generation of public administrators, so I am always looking for ways to improve! 

-----

## Syllabi

I highly recommend Checking out the site [PASyllabi.com](https://pasyllabi.com/) where many excellent syllabi have been uploaded. If you teach PA, Please consider uploading your syllabi there too.

[**Local Government Politics and Administration**](https://drive.google.com/file/d/1Ntm47wxYW86Cf6YeGmLBZmxDd8gTkxF4/view?usp=sharing)
-Last taught: Fall 2020

[**Governmental Budgeting**](https://drive.google.com/file/d/10KDs8zMDK_mGnHXDS-fcGZZTXXtKnjHH/view?usp=sharing)
-Last taught: Spring 2021

[**Introduction to Data Science**](https://drive.google.com/file/d/1Jc962NTRp4LGNEXoIwRb9qPmILPSejXo/view?usp=sharing)
-Last taught: Summer 2021

[**Public Administration (I use Parks and Recreation instead of a textbook in this course)**](https://drive.google.com/file/d/1FopItT1UG_lda3ImJxmOZLeb0GQBu8O1/view?usp=sharing)
-Last taught: Summer 2019

